services:
  postgres:
    image: postgres:17
    container_name: orders-postgres
    environment:
      POSTGRES_USER: orders
      POSTGRES_PASSWORD: orders
      POSTGRES_DB: orders
    ports:
      - "5436:5432"
    volumes:
      - orders-postgres-data:/var/lib/postgresql/data

  nats:
    image: nats:latest
    container_name: orders-nats
    command: ["-c", "/etc/nats/nats.conf"]
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - ./nats.conf:/etc/nats/nats.conf:ro
      - orders-nats-data:/data

  redis:
    image: redis:latest
    container_name: orders-redis
    ports:
      - "6379:6379"
    volumes:
      - orders-redis-data:/data

volumes:
  orders-postgres-data:
  orders-nats-data:
  orders-redis-data: